### ISSUE TITLE
Problem with mission items in AD Windy Valley

### ISSUE THREAD

**Issue by GamecubeGuy** [sonicretro/sa_tools#157]
I tried to add a mission flag to AD Windy Valley, but I ended up with a crash instead.

Error:
Program: SADXLVL2
Build Date: 03/05/2021 06:06:40
OS Version: Microsoft Windows NT 10.0.18363.0
Log:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Windows.Forms.TreeNodeCollection.get_Item(Int32 index)
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.Selection_SelectionChanged(EditorItemSelection sender) in D:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 140
   at SonicRetro.SAModel.SAEditorCommon.UI.EditorItemSelection.SelectionChangeHandler.Invoke(EditorItemSelection sender)
   at SonicRetro.SAModel.SAEditorCommon.UI.EditorItemSelection.Add(Item item) in D:\Programs\sa_tools\SAEditorCommon\UI\EditorItemSelection.cs:line 32
   at SonicRetro.SAModel.SADXLVL2.MainForm.missionObjectToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 2718
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Thanks for the report. This should now be fixed in the latest version along with some other issues with Mission SET items.
(Note that Mission SET items are hidden and unselectable by default, use the View and Layers menus to enable them)

**Comment by GamecubeGuy** [comment]
No problem. Is the latest version out already, or will it take a while before it's released?

**Comment by GamecubeGuy** [comment]
I ask because I downloaded the newest version and I still get the same error.

Error:
Program: SADXLVL2
Build Date: 03/05/2021 06:06:40
OS Version: Microsoft Windows NT 10.0.19042.0
Log:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Windows.Forms.TreeNodeCollection.get_Item(Int32 index)
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.Selection_SelectionChanged(EditorItemSelection sender) in D:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 140
   at SonicRetro.SAModel.SAEditorCommon.UI.EditorItemSelection.SelectionChangeHandler.Invoke(EditorItemSelection sender)
   at SonicRetro.SAModel.SAEditorCommon.UI.EditorItemSelection.Add(Item item) in D:\Programs\sa_tools\SAEditorCommon\UI\EditorItemSelection.cs:line 32
   at SonicRetro.SAModel.SADXLVL2.MainForm.missionObjectToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 2718
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by GamecubeGuy** [comment]
The newest version allows me to edit mission objects in the level. However, I'm having a problem loading them in-game. I took "SETMI0202M.bin" out of the project folder I saved it in and into a mod folder, but it doesn't seem to work. Is this because of the size, because it only says 1kb, which seems too small to me. I even put "_AD" after the "M", but it still doesn't work.

**Comment by GamecubeGuy** [comment]
Removing the "_AD" after "M" seemed to fix it. However, I added electric spinners to the level and they won't load, except for 2 of them, but they turned into Capsules and I can't seem to find out why. They don't have anything different except the rotation and positions. 
![image](https://user-images.githubusercontent.com/31381571/111718169-d434c280-882f-11eb-9420-1e41bf806bbc.png)
![image](https://user-images.githubusercontent.com/31381571/111718190-dc8cfd80-882f-11eb-9434-14423bb35535.png)
I would appreciate if you could help find the solutions.

**Comment by GamecubeGuy** [comment]
PRMMI0202M.bin also had to be copied over for the spinners to show up.
