### ISSUE TITLE
SADXLVL2: Unhandled exception error when loading boss, subgame and Chao levels

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#37]
Steps to reproduce:
1. Create a new project.
2. Run SADXLVL2.
3. Load any boss, subgame or Chao level.

Error details:
`Program: SADXLVL2
Build Date: 02/25/2019 04:09:20
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LoadFullTree() in E:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 203
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LevelData_StateChanged() in E:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 183
   at System.Action.Invoke()
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelData.InvalidateRenderState() in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelData.cs:line 144
   at SonicRetro.SAModel.SADXLVL2.MainForm.backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1522
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
`

**Comment by PiKeyAr** [comment]
Loading Ice Cap 1 triggers a similar error:
> Program: SADXLVL2
> Build Date: 03/01/2019 22:26:05
> OS Version: Microsoft Windows NT 6.2.9200.0
> Log:
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LoadFullTree() in E:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 203
>    at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LevelData_StateChanged() in E:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 183
>    at System.Action.Invoke()
>    at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelData.InvalidateRenderState() in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelData.cs:line 144
>    at SonicRetro.SAModel.SADXLVL2.MainForm.backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1522
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
>    at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
>

**Comment by jcorvinus** [comment]
fixed in commit 2b5773b15e7be78aaf76ae799a1af9922335839d

**Comment by PiKeyAr** [comment]
This was closed back in early March but the issue still persists as of today. I suggest merging that commit into master or reopening this.
